from __future__ import annotations

from collections.abc import Mapping
from typing import Any


def _profile(
    *,
    question: str,
    use_when: str,
    distinguish: str,
    trigger: str,
    owner: str,
    output: str,
    consumer: str,
    runtime: tuple[str, ...],
    construction: str,
    objects: tuple[tuple[str, str], ...],
    state: tuple[tuple[str, str, str, str], ...],
    choices: tuple[tuple[str, str, str], ...],
    supported: tuple[str, ...],
    unsupported: tuple[str, ...],
    take: tuple[str, ...],
    adapt: tuple[str, ...],
    avoid: tuple[str, ...],
    verify: tuple[str, ...],
    mechanism_model: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    mechanism = dict(mechanism_model or {
        "plain_summary": "这项能力由明确的数据结构和控制步骤组成；下面分别说明存取、决策与结束条件。",
        "storage": "该能力使用上方核心对象保存当前输入、状态与输出；具体持久化介质需结合源码证据确认。",
        "write_path": "输入经运行步骤处理后写入该能力负责的状态或输出对象。",
        "read_path": "执行器从当前状态读取所需输入；没有独立查询层时直接说明为按键或字段读取。",
        "control_loop": "按上方运行步骤推进；如果不是循环，明确为一次调用完成。",
        "decision_rules": "由显式条件、配置或返回值决定下一步，不能用调用链名称代替规则。",
        "termination": "产出结果、无后续步骤或命中保护上限时结束。",
        "dynamic_behavior": "默认只允许在运行前通过配置或注册改变结构；运行中的可变范围以源码合同为准。",
        "worked_example": list(runtime[:3]),
    })
    return {
        "question": question,
        "use_when": use_when,
        "distinguish": distinguish,
        "runtime_story": {
            "trigger": trigger,
            "owner": owner,
            "output": output,
            "consumer": consumer,
            "steps": list(runtime),
        },
        "construction": {
            "explanation": construction,
            "objects": [{"name": name, "role": role} for name, role in objects],
        },
        "mechanism_model": mechanism,
        "state_flow": [
            {"stage": stage, "reads": reads, "writes": writes, "why_next": why_next}
            for stage, reads, writes, why_next in state
        ],
        "design_choices": [
            {"choice": choice, "why": why, "cost": cost}
            for choice, why, cost in choices
        ],
        "boundary": {"supported": list(supported), "unsupported": list(unsupported)},
        "reuse_plan": {
            "take": list(take),
            "adapt": list(adapt),
            "avoid": list(avoid),
            "verify": list(verify),
        },
    }


_WAKU_CHAPTERS: dict[str, dict[str, Any]] = {
    "loop": _profile(
        question="怎样让模型不只回答一句话，而是持续调用工具，直到任务完成？",
        use_when="下一步动作必须由模型看到最新工具结果后才能决定，例如检查 PR、修复代码或调查故障。",
        distinguish="Loop 适合执行中发现步骤；Graph 适合事先已知节点和依赖。Graph 的某个节点也可以调用完整 Loop。",
        trigger="Waku 收到一轮用户消息，或 Graph 的 full_agent 节点把任务交给循环。",
        owner="run_loop 持有本轮 messages、工具注册表、迭代计数和 observer。",
        output="最终文本、完整消息历史、工具调用记录、耗时和停止原因。",
        consumer="CLI、Gateway、Voice、Dashboard 或上层 Graph 节点。",
        runtime=(
            "把用户消息和系统上下文组装成模型请求。",
            "模型返回普通文本或一个/多个工具调用。",
            "若有工具调用，ToolRegistry 执行并把结果追加为 observation。",
            "带着新 observation 再次请求模型，让下一步基于真实结果决定。",
            "模型不再调用工具时自然结束；否则达到 max_iterations 后强制停止。",
        ),
        construction="循环不是工作流 DSL，而是一段持有消息历史的控制循环；模型只决定下一动作，Python 代码负责工具执行、结果回填和终止门。",
        objects=(("messages", "本轮唯一的推理上下文"), ("ToolRegistry", "把模型调用名映射到真实函数"), ("observer", "把 reasoning/tool/result 事件送往界面"), ("max_iterations", "防止模型无限继续")),
        state=(("开始", "用户消息、历史、工具 schema", "第一条模型回复", "判断是否含工具调用"), ("工具阶段", "tool name + arguments", "tool result / error", "把 observation 回填给模型"), ("下一轮", "更新后的 messages", "下一动作或最终回答", "无工具调用则结束")),
        choices=(("同步循环", "控制流直观，消息顺序容易复现", "长工具会阻塞；取消和并发任务需另加协议"), ("双终止条件", "兼顾模型自然结束与系统硬上限", "达到上限时可能留下未完成任务"), ("错误作为 observation", "模型能看到失败并调整策略", "必须防止敏感异常文本直接泄漏")),
        supported=("多轮工具调用", "自然结束与最大迭代数", "observer 事件"),
        unsupported=("跨进程恢复", "多 Agent 并行调度", "工具级事务和自动补偿"),
        take=("reason → act → observe 骨架", "工具结果回填格式", "自然结束 + 硬上限"),
        adapt=("改成异步取消友好的执行器", "增加预算、审批、重试和任务隔离"),
        avoid=("直接绑定单一供应商响应类型", "把工具异常原样暴露给模型或用户"),
        verify=("连续工具调用次序", "达到上限的用户可见结果", "取消时是否仍有后台副作用"),
        mechanism_model={
            "plain_summary": "Agent Loop 就是一个有最大次数的 Python for 循环，不是 while：每轮让模型决定回答还是调用工具，有工具就执行并把结果放回 messages，再进入下一轮。",
            "storage": "没有独立工作流数据库；本轮状态保存在 messages 列表、ToolRegistry 与 LoopResult 中。messages 是推理上下文的事实源，observer 事件只是过程投影。",
            "write_path": "每次模型回复先追加到 messages；若含工具调用，则按顺序执行工具，并把 tool_result 作为新的 user observation 追加，供下一轮继续读取。",
            "read_path": "每轮模型请求都会读取当前完整 messages 与 tools.schemas；工具执行按 name 从 ToolRegistry 查找 callable，没有额外检索索引。",
            "control_loop": "显式执行 for iteration in range(1, max_iterations + 1)：reason → 检查 tool_uses → act → observe → 再次 reason。它确实是一个有上限的控制循环。",
            "decision_rules": "从模型 response.content 过滤 tool_uses；为空就把文本作为最终答案，有调用就按 name 分派并继续下一轮。",
            "termination": "两个出口：模型不再返回 tool_uses 时自然结束；或达到 max_iterations 后由系统强制停止。",
            "dynamic_behavior": "下一步工具名与参数可由模型动态决定，但可用工具必须事先注册；这里没有多 Agent 并行调度。",
            "worked_example": [
                "第 1 轮模型判断需要查询日历并返回 calendar_search 工具调用。",
                "Python 执行工具，把结果追加到 messages；第 2 轮模型基于真实结果决定是否继续。",
                "模型不再产生 tool_uses，循环返回最终文本；若一直调用则由 max_iterations 截止。",
            ],
        },
    ),
    "memory": _profile(
        question="怎样把聊天沉淀为可长期使用的事实和经历，又不在每轮都做昂贵总结？",
        use_when="助手需要跨会话记住稳定事实、人物偏好或过去事件，并允许后续检索。",
        distinguish="Memory 保存跨会话知识；当前轮 messages 只是短期上下文。consolidation 是整理过程，不是检索本身。",
        trigger="未整理聊天数量达到阈值，或上层显式请求 consolidation。",
        owner="consolidate_if_due 读取原始聊天，模型负责结构化提炼，SQLite store 负责持久化。",
        output="事实记录、episode 记录以及本批聊天已处理的游标/状态。",
        consumer="后续对话的记忆检索、Dashboard 记忆页和用户审阅工具。",
        runtime=("计算未整理聊天数量，未到阈值则直接返回。", "批量读取原始聊天并构造受限总结请求。", "模型把内容拆成 facts 与 episodes。", "解析结构化结果并分别写入两个 store。", "全部成功后推进 consolidation 状态；失败时保留原始聊天供重试。"),
        construction="它采用‘原始事件先保存、派生记忆后生成’的两层模型。阈值降低模型调用频率，两个 store 则把稳定事实与有时间语境的经历分开。",
        objects=(("chat store", "不可丢失的原始对话"), ("fact store", "可复用的稳定陈述"), ("episode store", "带时间与情境的经历"), ("consolidation cursor", "标记哪些原始聊天已经处理")),
        state=(("阈值判断", "未整理数量、配置阈值", "due / not due", "只有 due 才调用模型"), ("提炼", "一批原始聊天", "facts + episodes", "结构校验通过才允许写库"), ("提交", "派生记忆", "SQLite rows + 新游标", "后续检索看到新记忆")),
        choices=(("批量整理", "摊薄模型成本并获得跨消息语境", "记忆不是实时可见"), ("facts / episodes 分库", "检索意图更清楚", "同一信息可能跨库重复"), ("失败不推进游标", "避免静默丢记忆", "坏输入可能反复阻塞同一批次")),
        supported=("阈值触发", "事实/经历分离", "SQLite 本地持久化"), unsupported=("事实冲突自动消解", "删除传播与隐私生命周期", "记忆质量回归评测"),
        take=("原始记录与派生记忆分层", "阈值批处理", "成功后才推进游标"), adapt=("增加 provenance、冲突版本和删除策略", "为召回质量建立离线评测"), avoid=("模型输出未校验就写库", "把摘要当作唯一事实来源"), verify=("失败重试不重复写入", "冲突事实如何显示", "用户删除能否清理所有派生数据"),
        mechanism_model={
            "plain_summary": "Memory 先把原始聊天写进 state.db，再异步派生 facts 和 episodes；查询时先过 retrieval gate，再分别用 FTS5 召回、排序并合并结果。",
            "storage": "默认事实源是 ~/.waku/state.db：chat_log 保存原始 user/assistant 事件；facts 保存可复用的稳定事实；episodes 保存带 happened_at 的经历。facts_fts 与 episodes_fts 是可重建的 FTS5 派生索引，MEMORY.md 只是导出镜像，SKILL.md 属于程序性记忆。",
            "write_path": "log_chat 先把原始消息写入 chat_log 并提交。达到阈值后 consolidation 读取 consolidated=0 的批次，让模型派生 facts/episodes，分别写库成功后才标记原始行已整理；中途失败不会推进状态。",
            "read_path": "gated_retrieve 先让 retrieval gate 决定是否召回和生成 query；需要召回时，facts 把查询词清洗成 OR 表达式（CJK 使用前缀匹配），按 FTS5 rank 取 top_k；episodes 按 rank 再按 happened_at 降序取 3 条，最后把两类结果拼入上下文。",
            "control_loop": "每轮对话最多执行一次 gate → 两类检索 → 合并；整理是独立的周期批处理，不在每次查询时重新总结全部历史。",
            "decision_rules": "retrieval gate 决定本轮是否查询；facts 表达“长期成立什么”，episodes 表达“什么时候发生过什么”，因此分库存储和召回。gate 失败时采用保守的容错策略。",
            "termination": "检索在 facts top_k 与 episodes top 3 后结束；整理在未到阈值时直接结束，或在派生记录全部提交并标记原始批次后结束。",
            "dynamic_behavior": "事实/episode 后端可在启动配置中选择 SQLite、Supabase、Mem0、Zep、LangMem 或 Notion，但运行中不切换；原始聊天与派生记忆保持分层。",
            "worked_example": [
                "用户说‘我对花生过敏’，原始 user/assistant 消息先进入 chat_log，尚未直接冒充长期事实。",
                "达到整理阈值后，模型从未整理批次派生一条 fact；如果是‘上周去过杭州’，则生成带时间的 episode，并在全部成功后标记原始事件。",
                "以后询问饮食建议时 gate 允许召回，FTS5 对 facts/episodes 分别检索和排序，再把 top-K 结果合并给 Agent。",
            ],
        },
    ),
    "graph": _profile(
        question="怎样把已知任务拆成可并行节点，并在并发后仍得到确定、可解释的状态？",
        use_when="节点、依赖和主要分支能在执行前画出来，例如分类与日历并行，汇合后选择 quick reply 或 full agent。",
        distinguish="Graph 固定大流程和依赖；Loop 在执行中发现下一步。Waku 支持运行前按配置动态建图和运行时条件路由，但没有安全的运行中拓扑修改合同。",
        trigger="Waku.respond 选择 graph_workflows，或应用直接把 Graph 和初始 state 交给 run_graph。",
        owner="Graph 保存 Node/Edge/Router 拓扑；run_graph 维护 deps、fired、runs、path、errors 和共享 state。",
        output="合并后的 state、执行路径、节点事件、路由结果与失败状态。",
        consumer="Agent 应用取出 result；Dashboard/observer 展示各 wave 与节点状态。",
        runtime=("START 释放所有依赖已满足的节点，形成第一 wave。", "同 wave 节点读取同一个波前 state 浅拷贝，并由线程池并发执行。", "主线程等待整波完成，检测同 key 写冲突，再按稳定顺序提交结果。", "节点成功后标记出边 fired；只有全部入边已 fired 的 join 节点才进入下一 wave。", "router 在波次提交后读取新 state，选择预先注册的目标；max_visits 与 max_steps 限制循环。"),
        construction="图是普通 Python 对象：先注册 Node，再用 Edge 声明依赖，把 Router 挂在某个节点，最后执行。可以在 run_graph 前循环生成不同拓扑；运行中让 LLM 新增节点则缺少锁、版本、依赖重算和恢复协议。",
        objects=(("Node", "name + callable + kind + max_visits + on_error"), ("Edge", "源成功后触发目标的一条依赖"), ("Router", "读取已提交 state，用 label 选择预注册目标"), ("Wave", "共享波前快照与统一提交边界"), ("gather node", "无业务输出的显式 fan-in / join 屏障")),
        state=(("启动", "message、初始 errors", "classify/calendar ready", "二者只依赖 START"), ("Wave 1", "相同波前 state", "route/triage_reason + calendar", "写集分离，整波完成后统一合并"), ("gather", "已 fired 的两条入边", "不写业务数据", "deps[gather] ⊆ fired[gather] 才可运行"), ("router", "合并后的 route", "quick 或 full 目标", "目标在建图时已注册"), ("结束", "分支结果", "最终 state/path/errors", "到 END 或无 ready 节点")),
        choices=(("Wave 屏障", "保证同波读同一快照、提交顺序可复现", "比持续流水线少一部分并行度"), ("ThreadPoolExecutor", "同步节点接入简单", "不是 async 调度，也不提供进程隔离"), ("顶层 key 冲突检测", "避免并发结果静默覆盖", "嵌套对象和外部副作用仍需调用者保证"), ("代码 Router", "模型给分类，代码掌握控制流，便于测试", "动态目标必须预先注册")),
        supported=("运行前动态构图", "同 wave 并行", "显式 join", "条件路由", "有限循环"), unsupported=("运行中安全修改拓扑", "checkpoint / 崩溃恢复", "跨进程 worker", "分布式耐久调度"),
        take=("wave + commit barrier", "fan-in 就绪判断", "state collision", "max_visits/max_steps"), adapt=("为节点和图增加稳定 ID 与版本", "增加 checkpoint、幂等、取消和恢复"), avoid=("把 asyncio.gather 当作状态合并协议", "把进程内 Graph 当作持久工作流引擎"), verify=("同 wave 写冲突", "循环图终止", "节点失败后的路径", "进程在 merge 后崩溃的恢复"),
        mechanism_model={
            "plain_summary": "Graph 是进程内依赖图；Router 不是执行节点，它在一波节点提交后读取 state，把返回的 label 映射成下一条要激活的预注册分支。",
            "storage": "拓扑只存在进程内：nodes 字典、edges 列表、routers 字典；单次运行状态包含 deps、fired、runs、path、errors 和共享 state，没有持久化工作流数据库。",
            "write_path": "同一 wave 的节点读取同一份波前 state 浅拷贝并各自返回 patch；主线程等待整波完成，按稳定顺序合并，两个节点写同一顶层 key 时抛 GraphStateCollision。",
            "read_path": "next_wave 读取 jumps，并筛选 deps[node] 已全部包含在 fired[node]、且节点尚未超过 max_visits 的节点；这不是数据库查询，而是对内存依赖集合做就绪计算。",
            "control_loop": "run_graph 反复执行：计算 ready wave → ThreadPoolExecutor 并发运行本波 → 等待全部完成 → 合并 state → 标记出边 → 执行 router → 计算下一 wave。",
            "decision_rules": "普通 Edge 表示依赖完成；Router 在 wave 提交后调用 Python route(state) 得到 label，再映射到建图时预注册的目标。模型可以写 route 字段，但真正控制边的是代码 router。",
            "termination": "没有 ready 节点、到达 END、超过全局 max_steps，或某节点达到 max_visits 时停止；错误按节点 on_error 策略记录或终止。",
            "dynamic_behavior": "可以在 run_graph 前用 Python/配置循环创建节点、边和 router，即运行前动态构图；运行中修改拓扑没有锁、版本、依赖重算和恢复合同，因此不支持安全动态加节点。",
            "worked_example": [
                "START 同时释放 classify 与 check_calendar，因为二者只依赖 START；它们读取同一波前快照，适合并发等待。",
                "gather 有两条入边，只有 classify 和 calendar 都完成、两条依赖都 fired 后才会进入下一 wave；并发本身不是关键，显式 join 才是。",
                "gather 后 router 读取已合并的 route 字段，用 label 选择 quick_reply 或 full_agent；目标必须在运行前注册。",
            ],
        },
    ),
    "gateway": _profile(
        question="怎样让 CLI、Web 和多个消息通道共享同一个 Agent，同时能独立启动、停止和重载？",
        use_when="同一助手需要长期运行在多个本地或远程通道，并随配置变化增删通道。",
        distinguish="Gateway 管通道生命周期，不负责模型推理；Loop 执行任务，Dashboard 只是其中一个操作面。",
        trigger="Gateway CLI 启动 supervisor，或 Dashboard 请求重载通道配置。",
        owner="GatewaySupervisor 持有配置指纹、活动 runner、停止信号和状态回调。",
        output="正在运行的通道集合、健康/错误状态以及进入 Waku 的规范化消息。",
        consumer="各 channel runner、Dashboard 状态页以及共享 Waku 实例。",
        runtime=("读取 gateway 配置并计算每个通道的稳定指纹。", "reconcile 比较期望配置与当前 runner。", "新增通道被启动，删除通道被停止，指纹变化的通道被重建。", "runner 把外部消息规范化后交给共享 Waku。", "回复被 adapter 转回各通道格式；状态变化通过 provider 暴露。"),
        construction="Supervisor 是唯一生命周期控制面；每个通道只实现 start/stop/message adapter。配置指纹让 reconcile 不必猜测对象是否真的改变。",
        objects=(("GatewaySupervisor", "期望状态与实际 runner 的协调器"), ("channel runner", "一个通道的连接和收发循环"), ("fingerprint", "判断配置是否需要重建"), ("status provider", "向 Dashboard 暴露当前状态")),
        state=(("启动", "gateway config", "desired channel set", "reconcile 与实际集合比较"), ("协调", "desired + running", "start/stop/restart actions", "使实际集合收敛"), ("消息", "channel event", "normalized Waku request", "共享 Agent 生成回复")),
        choices=(("单一 Supervisor", "避免各入口各自管理线程和连接", "成为生命周期故障集中点"), ("指纹式重载", "配置变化判断简单确定", "指纹遗漏字段会导致旧 runner 未重建"), ("共享 Agent", "跨通道能力一致", "并发会话隔离必须另行保证")),
        supported=("通道启动/停止/重建", "配置变化协调", "状态暴露"), unsupported=("多机器通道编排", "统一认证与租户隔离", "可靠消息队列语义"),
        take=("adapter + supervisor 边界", "reconcile 状态机", "配置指纹"), adapt=("增加会话隔离、重连退避和幂等消息 ID", "为各通道建立真实设备测试"), avoid=("每个入口自行创建 Agent", "把线程存活当作健康"), verify=("配置热重载", "重复消息", "断线恢复", "并发通道之间的状态污染"),
        mechanism_model={
            "plain_summary": "Gateway 是通道生命周期协调器：比较配置与当前 runner，决定启动、停止或重建，再把各通道消息交给同一个 Waku。",
            "storage": "进程内保存 desired channel config、按通道名索引的 active runners、配置 fingerprint 与健康状态；没有耐久消息队列或跨进程任务表。",
            "write_path": "reconcile 计算差异后启动新增 runner、停止已删除 runner，并对 fingerprint 变化的通道执行 stop → rebuild → start；状态回调更新 Dashboard 可见健康信息。",
            "read_path": "协调器读取期望配置与当前 runner 集合，按通道名和 fingerprint 做精确比较；这属于状态协调查询，不是全文检索。",
            "control_loop": "Supervisor 周期性/事件式执行 read config → diff → start/stop/restart → publish status；每个 runner 另有自己的收发循环。",
            "decision_rules": "通道不存在则 start，期望中删除则 stop，fingerprint 改变则 rebuild，相同则保留；外部消息经 adapter 规范化后进入共享 Waku。",
            "termination": "Supervisor 收到停止信号后停止所有 runner；单个 runner 在通道被删除、重建或连接终止时退出。",
            "dynamic_behavior": "运行时可以通过配置增删或重建通道，但不能把 runner 迁移到另一台机器，也没有分布式 leader/lease。",
            "worked_example": ["Telegram 配置首次出现，reconcile 创建并启动 runner。", "token 配置变化导致 fingerprint 改变，旧 runner 先停止再重建。", "消息经 adapter 变成统一请求，共享 Waku 回复后再转回 Telegram 格式。"],
        },
    ),
    "voice": _profile(
        question="怎样把本地麦克风、语音识别、Agent 和朗读串成一个可用的语音入口？",
        use_when="需要本地按键说话或唤醒式交互，并接受轮次式而非原生全双工对话。",
        distinguish="这是 VAD/录音 → ASR → 文本 Agent → TTS 的串联系统，不是端到端全双工语音模型。",
        trigger="用户按键开始录音，或 wake loop 检测到唤醒条件。",
        owner="Ears 管采集/转写，Waku 管文本任务，Mouth 管 TTS 播放。",
        output="转写文本、Agent 回复文本和扬声器音频。",
        consumer="本地用户；observer/Dashboard 可接收同一轮事件。",
        runtime=("麦克风采集 PCM，按键或唤醒状态决定何时结束一段。", "本地 Whisper 把完整音频片段转成文本。", "空文本被忽略；有效文本交给 Waku.respond。", "Agent 可能执行工具或 Graph，最终产生回复文本。", "Mouth 把回复送入 TTS 并播放，然后才进入下一轮监听。"),
        construction="语音层由三个串联 adapter 组成，文本是 ASR、Agent 和 TTS 之间的稳定边界，因此可以独立替换任一段。",
        objects=(("Ears", "录音和 ASR"), ("wake_loop", "控制监听/唤醒轮次"), ("Waku", "文本推理与工具执行"), ("Mouth", "TTS 和音频播放")),
        state=(("监听", "mic frames", "一段音频", "结束条件触发 ASR"), ("转写", "audio segment", "text", "非空文本进入 Agent"), ("回答", "text + context", "reply text", "交给 TTS"), ("播放", "reply text", "audio output", "播放结束后恢复监听")),
        choices=(("文本中间层", "ASR/LLM/TTS 可分别替换", "丢失端到端声学信息和更低延迟机会"), ("轮次式播放", "实现简单、不易自激", "不能自然打断"), ("本地 ASR", "隐私与离线能力更好", "设备性能和模型加载成本更高")),
        supported=("按键/唤醒轮次", "本地 Whisper ASR", "文本 Agent", "TTS 朗读"), unsupported=("真正全双工", "barge-in 打断", "AEC 回声消除", "流式增量 ASR→LLM→TTS"),
        take=("Ears/Waku/Mouth 解耦", "文本协议边界", "本地优先 ASR"), adapt=("加入 VAD、流式队列、取消传播和播放打断", "建立端到端延迟预算"), avoid=("把这套轮次架构宣称为全双工", "播放期间继续把扬声器声音送回 ASR"), verify=("噪声下分段", "首字延迟", "打断与取消", "不同声卡/采样率"),
        mechanism_model={
            "plain_summary": "Voice 是串行轮次链：录音结束后才依次执行 ASR → Agent → TTS；播放结束才回到监听，所以它不是实时全双工。",
            "storage": "单轮只保存麦克风 PCM buffer、完整 transcript、Agent reply 与待播放音频；它没有独立长期记忆，跨轮知识由 Waku Memory 负责。",
            "write_path": "Ears 连续写入 PCM frame，结束一段后把完整 buffer 交给 Whisper；转写文本写入本轮请求，回复文本再写入 Mouth/TTS 播放队列。",
            "read_path": "ASR 顺序读取完整音频段，Waku 读取 transcript，TTS 读取最终 reply；没有语义搜索或 Top-K 查询层。",
            "control_loop": "listen/record → segment end → ASR → Waku.respond → TTS/play → 回到 listen，是轮次循环而非同时收听和说话。",
            "decision_rules": "按键或 wake 状态决定录音边界；空 transcript 被忽略；只有 Agent 产生最终文本后才开始 TTS。",
            "termination": "一轮在播放结束后完成；全局 stop 终止监听。当前没有 barge-in，因此播放中用户不能自然打断本轮。",
            "dynamic_behavior": "ASR/TTS adapter 可在启动时替换，运行中仍按固定串联管线推进；没有端到端全双工模型和流式跨段调度。",
            "worked_example": ["用户按键说话，Ears 缓存 PCM 直到松键。", "Whisper 生成完整文本，Waku 可能再执行工具或 Graph。", "最终文字交给 Mouth 播放，播放结束后才恢复监听。"],
        },
    ),
    "tools": _profile(
        question="怎样把模型给出的工具名和 JSON 参数安全地映射到真实 Python 能力？",
        use_when="Agent 需要调用日历、文件、搜索或 MCP 工具，并让失败结果回到推理循环。",
        distinguish="Registry 解决描述、查找和分派；它本身不是权限系统、沙箱或远程任务调度器。",
        trigger="模型回复中出现 tool call；Loop 把名称和参数交给 ToolRegistry。",
        owner="ToolRegistry 保存 tool schema 与 callable，Loop 管调用次序和结果回填。",
        output="结构化/文本工具结果，或经过边界化的错误 observation。",
        consumer="同一轮模型推理以及 observer/UI。",
        runtime=("启动时注册 name、description、JSON schema 与 callable。", "请求模型时把所有 schema 暴露为可选工具。", "模型返回 tool name + arguments。", "Registry 查找并调用对应函数。", "结果或错误转成 observation，追加到 messages 后继续 Loop。"),
        construction="最小 Tool 对象把模型看到的契约与实际 Python 实现绑定；Registry 只负责名字唯一性和调用分派，让 Loop 不需要知道每个工具细节。",
        objects=(("Tool", "名称、描述、参数 schema、callable"), ("ToolRegistry", "注册、列出和 dispatch"), ("tool result", "回到模型的 observation"), ("observer", "显示调用进度")),
        state=(("注册", "tool definition", "registry entry", "模型请求能看到 schema"), ("分派", "name + arguments", "return value / exception", "标准化为 observation"), ("回填", "tool result", "updated messages", "模型决定下一步")),
        choices=(("统一 Registry", "Loop 与具体工具解耦", "所有能力共享同一信任边界"), ("异常转 observation", "模型可纠错", "错误文本需脱敏"), ("JSON schema", "模型和程序有共同参数合同", "运行时仍需类型/业务校验")),
        supported=("本地函数注册", "schema 暴露", "异常隔离"), unsupported=("权限审批", "OS 沙箱", "强制超时", "远程 MCP 生命周期与断线恢复"),
        take=("最小 Tool 契约", "registry dispatch", "错误回填"), adapt=("增加 principal、risk、timeout、idempotency 元数据", "把执行放进隔离 worker"), avoid=("模型可调用任意注册函数", "仅靠 JSON schema 作为安全校验"), verify=("越权参数", "超时与取消", "重复调用副作用", "敏感异常脱敏"),
        mechanism_model={
            "plain_summary": "Tools 是 name → schema/callable 的注册与精确分派层；它执行一次工具调用，是否继续由外层 Agent Loop 决定。",
            "storage": "ToolRegistry 用进程内 name → Tool 映射保存 description、JSON schema 与 callable；它不保存业务数据，也不是权限库。",
            "write_path": "应用启动时显式 register 工具；执行结果不写回 Registry，而是由 Loop 追加到 messages 作为 observation。",
            "read_path": "模型请求读取所有 tools.schemas；分派时按返回的 tool name 做精确查找，再把 arguments 交给 callable，没有模糊搜索。",
            "control_loop": "Registry 自身不是循环，只完成 lookup → validate/dispatch → return；外层 Agent Loop 决定是否根据结果再次调用工具。",
            "decision_rules": "只有已注册 name 可执行；未知 name 或调用异常转成受控错误 observation。JSON schema 描述参数，但仍需要运行时业务校验。",
            "termination": "单次工具函数返回或抛出边界化异常即结束；超时、取消和补偿不是 Registry 当前合同。",
            "dynamic_behavior": "启动阶段可增删工具；模型只能动态选择已注册工具和参数，不能生成任意 Python 函数。",
            "worked_example": ["应用注册 calendar_search 及其参数 schema。", "模型返回 name=calendar_search，Registry 精确找到 callable 并执行。", "结果追加到 messages，是否继续调用由外层 Loop 决定。"],
        },
    ),
    "providers": _profile(
        question="怎样让同一个 Agent Loop 使用不同模型供应商，而不把协议差异扩散到业务逻辑？",
        use_when="需要在 Anthropic 与 OpenAI-compatible 服务之间切换，并保持统一的文本和工具调用流程。",
        distinguish="Provider adapter 统一模型协议；它不负责 Agent 的循环、工具实现或业务工作流。",
        trigger="启动时根据配置选择 provider，或请求前构建对应 client。",
        owner="get_client 与各 provider client 负责请求/响应规范化；Loop 只消费统一表面。",
        output="统一的文本块、工具调用和停止原因。",
        consumer="run_loop、评测和上层应用。",
        runtime=("读取 provider、model、base URL、key 与 timeout。", "纠正不属于该 provider 的继承模型名/配置。", "把统一 messages/tools 转成供应商 wire format。", "发送请求并接收原生响应。", "把文本、tool calls 和 stop reason 映射回 Loop 可消费形态。"),
        construction="适配器放在 Loop 外部，以公共子集作为稳定接口；供应商特有能力要么显式扩展，要么明确有损降级。",
        objects=(("provider config", "选择供应商和模型"), ("client adapter", "wire protocol 转换"), ("normalized response", "Loop 使用的共同形态"), ("timeout/error mapping", "跨供应商错误边界")),
        state=(("选择", "provider config", "client", "构造该供应商请求"), ("请求", "normalized messages/tools", "native response", "适配器解析"), ("归一化", "native blocks", "text/tool calls/stop", "Loop 继续")),
        choices=(("薄适配", "维护成本低、Loop 简洁", "只能覆盖供应商公共子集"), ("配置归属检查", "避免模型名/key 串供应商", "自定义兼容服务可能需要例外"), ("统一错误表面", "上层易处理", "会损失原生错误细节")),
        supported=("Anthropic/OpenAI-compatible 选择", "消息和工具调用归一化"), unsupported=("所有流式事件等价", "推理块/缓存等专有能力完整保真", "自动 fallback 的质量一致性"),
        take=("adapter 放在 Loop 外", "配置 owner 检查", "normalized response"), adapt=("建立 capability negotiation", "逐 provider 做流式与工具协议测试"), avoid=("只换 base_url 就假设兼容", "把一个 provider 的模型默认值带到另一个"), verify=("tool call/result 往返", "stream block 次序", "超时/限流映射", "专有字段降级"),
        mechanism_model={
            "plain_summary": "Providers 是模型协议适配层：按配置选择供应商，把统一消息转成原生请求，再把原生响应还原成 Loop 能理解的文本和工具调用。",
            "storage": "启动配置保存 provider、model、base URL、key 引用与 timeout；client adapter 保持连接配置，不建立独立对话数据库，消息事实源仍是 Loop.messages。",
            "write_path": "adapter 把统一 messages/tools 编码为供应商请求，并把原生响应归一化为 text/tool_calls/stop reason；不会把响应偷偷写入长期状态。",
            "read_path": "get_client 按 provider 配置精确选择 adapter，并读取该供应商拥有的模型与凭据；没有模型搜索或自动质量排名。",
            "control_loop": "单次 adapter 调用是 normalize request → HTTP SDK call → normalize response；多轮循环由上层 run_loop 驱动。",
            "decision_rules": "provider 字段选择 Anthropic 或 OpenAI-compatible 路径；不属于该 provider 的继承模型名会被纠正或拒绝。",
            "termination": "供应商返回 stop/tool call 或请求超时/报错时结束一次调用；自动 fallback 当前不是稳定合同。",
            "dynamic_behavior": "每次启动/构建 client 时可换 provider；运行中的一轮不会无声明地跨 provider，专有能力只按公共接口保守降级。",
            "worked_example": ["配置选择 OpenAI-compatible，并校验 model/key 归属。", "adapter 转换 messages 和 tools 后发送请求。", "原生 tool call 被归一化，Loop 不需要知道供应商 wire format。"],
        },
    ),
    "dashboard": _profile(
        question="怎样把聊天、工具、图、记忆和运行事件变成一个本地可观察、可操作的界面？",
        use_when="开发者需要查看 Agent 正在做什么、管理本地数据并触发少量控制操作。",
        distinguish="Dashboard 是控制/观察面；observer 是事件事实源；Gateway 才负责长期通道生命周期。",
        trigger="用户启动 dashboard 命令并在浏览器发起页面/API 请求。",
        owner="本地 Web handler 处理请求，observer/status provider 提供运行状态，共享 Waku 执行任务。",
        output="HTML/JSON/SSE 响应、聊天结果、trace、memory 和 gateway 状态。",
        consumer="本机用户与调试者。",
        runtime=("HTTP handler 接收页面或动作请求。", "只读请求从 store/provider 汇总状态。", "聊天/重载等动作调用共享 Waku 或 Gateway 控制面。", "observer 事件被转换为页面可消费的流。", "前端按事件 kind 更新视图并在终态封口。"),
        construction="页面不从日志反推执行过程，而是消费运行时 observer 事件；Web handler 只做输入校验、调用协调和响应转换。",
        objects=(("HTTP handler", "页面/API 边界"), ("observer stream", "运行时事件事实源"), ("status providers", "memory/graph/gateway 等只读状态"), ("shared Waku", "真正执行聊天和工具")),
        state=(("页面读取", "stores/providers", "snapshot JSON", "前端渲染"), ("执行动作", "validated request", "Waku/Gateway action", "observer 产生事件"), ("流式更新", "runtime events", "UI cards/turn state", "终态事件关闭本轮")),
        choices=(("本地单体 Web", "零部署、调试方便", "认证和多用户隔离弱"), ("observer 驱动", "UI 与真实运行过程一致", "事件 schema 成为稳定接口"), ("共享 Agent", "界面与其他入口能力一致", "并发请求需隔离会话")),
        supported=("本地聊天与状态视图", "运行事件展示", "少量控制动作"), unsupported=("公网安全部署", "多租户 RBAC", "完整审计与合规日志"),
        take=("observer 作为事实源", "read model / action handler 分离", "本地调试界面"), adapt=("增加认证、CSRF、会话隔离和并发控制", "明确每个写操作审批"), avoid=("把 localhost 当身份认证", "结束后从普通日志拼 trace"), verify=("恶意网页触发本地动作", "并发会话污染", "SSE 断线重连", "路径逃逸"),
        mechanism_model={
            "plain_summary": "Dashboard 是观察与操作面：读状态快照、消费 observer 事件，并把明确的用户动作转交给 Waku/Gateway，本身不执行 Agent 推理。",
            "storage": "Dashboard 不复制核心业务库；只读页从 Memory/store/status provider 取快照，进行中的 trace 以 observer 事件流为事实源，浏览器保存当前视图状态。",
            "write_path": "聊天或重载等 HTTP action 经过校验后调用共享 Waku/Gateway；执行产生的 observer event 被写入 SSE/页面流，而不是事后从普通日志推断。",
            "read_path": "页面/API 按资源读取 memory、graph、gateway 等 read model；事件流按 kind/turn 过滤后增量渲染，没有跨仓语义检索。",
            "control_loop": "request handler 校验 → 调用业务控制面 → observer 持续推送事件 → 前端按事件更新 → terminal event 封口。",
            "decision_rules": "GET/只读请求只访问 provider；明确 action 才能触发 Waku 或 Gateway 写操作。前端按 event kind 选择对应卡片更新。",
            "termination": "普通请求在响应返回时结束；SSE 在 terminal event、客户端断开或服务停止时结束。",
            "dynamic_behavior": "视图和事件卡可以按 schema 扩展，但 Dashboard 不动态改写 Agent 拓扑；公网认证、多租户与 RBAC 未实现。",
            "worked_example": ["用户提交聊天 action，handler 校验后调用共享 Waku。", "Loop/Graph 通过 observer 发送 reasoning、tool 与 result 事件。", "浏览器按 turn 更新卡片，terminal event 到达后结束该轮。"],
        },
    ),
    "eval": _profile(
        question="怎样让评测结果真正控制版本是否可发布，而不是只生成一份没人看的分数？",
        use_when="需要把确定性测试和模型质量评价组合成明确的 release gate。",
        distinguish="确定性检查是硬门；模型裁判是有波动的质量信号，二者不能被一个平均分互相抵消。",
        trigger="开发者或 CI 执行 release_gate 命令。",
        owner="release gate 编排 suite、judge、阈值与持久化报告，并用退出状态表达结果。",
        output="各子门结果、总 verdict、评测记录和 CLI exit code。",
        consumer="开发者、CI/CD 和版本发布流程。",
        runtime=("读取评测配置、provider 与阈值。", "先运行确定性 suites；任何硬失败直接关闭 gate。", "硬门通过后运行模型 judge，并显式处理缺 key/超时。", "保存每项结果、版本和配置。", "根据策略输出 GATE OPEN/CLOSED 与非零退出码。"),
        construction="Gate 是布尔决策器而不是平均分计算器：硬约束与统计质量分别保存，再由明确策略组合。",
        objects=(("deterministic suites", "必须完全通过的回归"), ("model judge", "主观质量信号"), ("threshold policy", "组合规则"), ("evaluation record", "可追溯 lineage")),
        state=(("硬门", "code/tests/protocol", "pass/fail", "fail 直接关闭"), ("质量门", "cases + judge config", "scores/reasons", "按阈值判断"), ("发布判定", "all gate results", "open/closed + exit code", "CI 决定是否继续")),
        choices=(("硬门优先", "严重回归不能被高主观分掩盖", "输出比单一总分复杂"), ("结果持久化", "以后能解释为何放行", "要管理评测数据版本"), ("缺裁判配置显式降级", "避免无 key 时伪成功", "本地体验可能更严格")),
        supported=("确定性 suite", "模型 judge", "发布 verdict 与记录"), unsupported=("测试集代表性自动保证", "裁判漂移消除", "完整 CI/审批治理"),
        take=("硬门与软门分离", "verdict 直接控制 exit code", "保存 lineage"), adapt=("绑定 commit/dataset/prompt/model 版本", "加入重复采样与置信区间"), avoid=("把所有分数做加权平均", "无 API key 时默认通过"), verify=("硬失败绝不放行", "judge 波动", "配置缺失", "历史结果可重放"),
        mechanism_model={
            "plain_summary": "Eval 是顺序发布门：先跑不可被抵消的确定性硬门，再跑模型质量门，最后用 verdict 和退出码决定是否允许发布。",
            "storage": "评测配置、用例、deterministic 结果、judge 分数/理由与最终 verdict 构成 evaluation record；记录应绑定代码和配置版本，而不是只保留一个总分。",
            "write_path": "每个 suite/judge 完成后写入独立结果；最终策略把各门组合成 OPEN/CLOSED，并用 CLI exit code 写给 CI。硬门失败不会被软分数覆盖。",
            "read_path": "release gate 读取固定评测配置、阈值和历史/当前结果；它按命名 gate 聚合，不进行向量搜索或 Top-K 召回。",
            "control_loop": "load config → deterministic suites → 若全过则 model judge → threshold policy → persist record → emit exit code。",
            "decision_rules": "任一确定性硬门失败立即 CLOSED；硬门全过后 judge 仍必须达到阈值。缺 key、超时或配置不完整不能静默当作通过。",
            "termination": "硬门首次失败可提前结束；否则在所有质量门完成并持久化 verdict 后结束。",
            "dynamic_behavior": "suite、case 和阈值可在运行前配置；执行中不会根据当前分数临时删测试，也不把不同版本结果混为同一 lineage。",
            "worked_example": ["先运行协议与回归 suites，一项失败则直接 CLOSED。", "硬门全过才调用 model judge，并保存分数、理由与模型配置。", "threshold policy 输出 verdict，非零 exit code 阻止 CI 发布。"],
        },
    ),
}


def discover_human_chapter(feature: Mapping[str, Any]) -> dict[str, Any]:
    """Return a human tutorial chapter for audited Waku mechanisms.

    Entry points and symbol paths are intentionally absent from the narrative.
    The report renders them later as evidence, after the reader understands the
    product capability and its runtime contract.
    """

    tags = feature.get("technology_tags")
    if not isinstance(tags, list) or "compatibility-corpus:waku-not-curated" not in tags:
        return {}
    mechanism = next(
        (
            str(tag).split(":", 1)[1]
            for tag in tags
            if isinstance(tag, str) and tag.startswith("compatibility-mechanism:")
        ),
        "",
    )
    template = _WAKU_CHAPTERS.get(mechanism)
    if template is None:
        return {}
    return {"mechanism": mechanism, **template}
